# Generated by Django 4.0.6 on 2022-07-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft_details',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nft_details',
            name='order_id',
        ),
        migrations.AddField(
            model_name='nft_details',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.product'),
        ),
        migrations.AddField(
            model_name='nft_details',
            name='token_id',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='nft_details',
            name='token_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nft_details',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='nft_details',
            name='expiry_date',
            field=models.DateTimeField(default=''),
        ),
    ]
