# Generated by Django 4.0.6 on 2022-07-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_nft_details_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft_details',
            name='acc_address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
