# Generated by Django 4.0.6 on 2022-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_nft_details_acc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft_details',
            name='token_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
