# Generated by Django 4.0.6 on 2022-07-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_nft_details_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft_details',
            name='redeem',
            field=models.BooleanField(default=True),
        ),
    ]
